package mesh.codegen

import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import mesh.model.AnimationState
import mesh.model.BezierDirection
import mesh.model.LoopMode
import mesh.model.MeshData
import mesh.model.MeshInterpolator
import mesh.model.SegmentEasing
import kotlin.math.abs
import kotlin.math.round
import kotlin.math.roundToInt

/**
 * Turns a [MeshData] into ready-to-paste Kotlin source that reproduces the same gradient.
 *
 * The output uses [androidx.compose.ui.graphics.MeshGradientPainter] painted through
 * `Modifier.paint`. This is the converged API: Compose Multiplatform 1.12.0-beta01+ and Jetpack
 * Compose (androidx.compose.ui 1.12.0-beta01+) both expose it, so the same snippet compiles on
 * either. (Early Android alphas up to 1.12.0-alpha03 shipped a `Modifier.meshGradient` extension
 * instead; it was replaced by the painter in 1.12.0-beta01.)
 *
 * Formatting rules:
 * - Colors are emitted as `Color(0xAARRGGBB)`.
 * - Floats use an `f` suffix and are rounded to at most 4 decimals, trailing zeros trimmed.
 * - Bezier control points equal to [Offset.Unspecified] are omitted to keep the code short.
 */
object KotlinCodeGenerator {

    private const val HEADER =
        "// Works with Compose Multiplatform 1.12.0-beta01+ and Jetpack Compose UI 1.12.0-beta01+ (MeshGradientPainter)."

    private val IMPORTS = listOf(
        "androidx.compose.foundation.layout.Box",
        "androidx.compose.foundation.layout.fillMaxSize",
        "androidx.compose.runtime.Composable",
        "androidx.compose.runtime.remember",
        "androidx.compose.ui.Modifier",
        "androidx.compose.ui.draw.paint",
        "androidx.compose.ui.geometry.Offset",
        "androidx.compose.ui.graphics.Color",
        "androidx.compose.ui.graphics.MeshGradientPainter",
    )

    private val ANIMATED_IMPORTS = listOf(
        "androidx.compose.animation.core.LinearEasing",
        "androidx.compose.animation.core.RepeatMode",
        "androidx.compose.animation.core.animateFloat",
        "androidx.compose.animation.core.infiniteRepeatable",
        "androidx.compose.animation.core.rememberInfiniteTransition",
        "androidx.compose.animation.core.tween",
        "androidx.compose.foundation.layout.Box",
        "androidx.compose.foundation.layout.fillMaxSize",
        "androidx.compose.runtime.Composable",
        "androidx.compose.runtime.getValue",
        "androidx.compose.runtime.remember",
        "androidx.compose.ui.Modifier",
        "androidx.compose.ui.draw.paint",
        "androidx.compose.ui.geometry.Offset",
        "androidx.compose.ui.geometry.lerp",
        "androidx.compose.ui.graphics.Color",
        "androidx.compose.ui.graphics.MeshGradientPainter",
        "androidx.compose.ui.graphics.lerp",
    )

    /**
     * Generates a full composable snippet for [mesh].
     *
     * @param hasBicubicColor value passed to `MeshGradientPainter(hasBicubicColor = ...)`.
     * @param includeImports when true, prepends the required `import` lines and a short header.
     */
    fun generate(
        mesh: MeshData,
        hasBicubicColor: Boolean,
        includeImports: Boolean = true,
    ): String = buildString {
        if (includeImports) {
            appendLine("// Generated by MeshGradient Designer.")
            appendLine(HEADER)
            IMPORTS.forEach { appendLine("import $it") }
            appendLine()
        }
        appendLine("@Composable")
        appendLine("fun MeshGradient(modifier: Modifier = Modifier) {")
        appendLine("    val painter = remember {")
        append("        MeshGradientPainter(")
        append("rows = ${mesh.rows}, columns = ${mesh.columns}, ")
        appendLine("hasBicubicColor = $hasBicubicColor) {")
        for (row in 0..mesh.rows) {
            for (column in 0..mesh.columns) {
                appendLine("            ${vertexCall(mesh, row, column)}")
            }
        }
        appendLine("        }")
        appendLine("    }")
        appendLine("    Box(modifier.fillMaxSize().paint(painter))")
        append("}")
    }

    /**
     * Generates code for an [AnimationState]: a single keyframe falls back to the static
     * [generate] output, while two or more keyframes produce a self-contained animated snippet.
     */
    fun generate(state: AnimationState, includeImports: Boolean = true): String =
        if (state.isAnimated) {
            generateAnimated(state, includeImports)
        } else {
            generate(state.keyframes.first(), state.hasBicubicColor, includeImports)
        }

    /**
     * Generates a self-contained animated composable: keyframe data, a `lerp` helper, a progress
     * mapping, and a `rememberInfiniteTransition` driving the interpolation.
     *
     * [LoopMode.PingPong] emits the keyframes as-is with `RepeatMode.Reverse`; [LoopMode.Cycle]
     * appends the first keyframe and uses `RepeatMode.Restart` so the wrap is seamless. The painter
     * is created once (`remember` without keys) and samples the animation by reading `progress`
     * inside its block: `MeshGradientPainter` executes the block on every draw, so each frame
     * invalidates the draw phase only — no recomposition and no painter re-allocation.
     */
    internal fun generateAnimated(state: AnimationState, includeImports: Boolean = true): String =
        buildString {
            val emitted = MeshInterpolator.effectiveKeyframes(state.keyframes, state.loopMode)
            val rows = state.keyframes.first().rows
            val columns = state.keyframes.first().columns
            val repeatMode = if (state.loopMode == LoopMode.PingPong) "Reverse" else "Restart"
            val segments = emitted.size - 1
            val totalDuration = state.durationMillisPerSegment * segments

            if (includeImports) {
                appendLine("// Generated by MeshGradient Designer.")
                appendLine(HEADER)
                ANIMATED_IMPORTS.forEach { appendLine("import $it") }
                appendLine()
            }

            // Keyframe data. Bezier offsets are resolved to their directional defaults so they can
            // be interpolated (Offset.Unspecified cannot be lerped).
            appendLine("private class MeshFrame(")
            appendLine("    val positions: List<Offset>,")
            appendLine("    val colors: List<Color>,")
            appendLine("    val left: List<Offset>,")
            appendLine("    val top: List<Offset>,")
            appendLine("    val right: List<Offset>,")
            appendLine("    val bottom: List<Offset>,")
            appendLine(")")
            appendLine()
            appendLine("private val keyframes: List<MeshFrame> = listOf(")
            emitted.forEach { frame ->
                appendLine("    MeshFrame(")
                appendLine("        positions = ${offsetList(frame.positions)},")
                appendLine("        colors = ${colorList(frame.colors)},")
                appendLine("        left = ${resolvedBezierList(frame.leftBezierOffsets, BezierDirection.LEFT)},")
                appendLine("        top = ${resolvedBezierList(frame.topBezierOffsets, BezierDirection.TOP)},")
                appendLine("        right = ${resolvedBezierList(frame.rightBezierOffsets, BezierDirection.RIGHT)},")
                appendLine("        bottom = ${resolvedBezierList(frame.bottomBezierOffsets, BezierDirection.BOTTOM)},")
                appendLine("    ),")
            }
            appendLine(")")
            appendLine()

            // Interpolation helpers.
            appendLine("private fun lerpFrame(a: MeshFrame, b: MeshFrame, t: Float): MeshFrame = MeshFrame(")
            appendLine("    positions = a.positions.mapIndexed { i, v -> lerp(v, b.positions[i], t) },")
            appendLine("    colors = a.colors.mapIndexed { i, v -> lerp(v, b.colors[i], t) },")
            appendLine("    left = a.left.mapIndexed { i, v -> lerp(v, b.left[i], t) },")
            appendLine("    top = a.top.mapIndexed { i, v -> lerp(v, b.top[i], t) },")
            appendLine("    right = a.right.mapIndexed { i, v -> lerp(v, b.right[i], t) },")
            appendLine("    bottom = a.bottom.mapIndexed { i, v -> lerp(v, b.bottom[i], t) },")
            appendLine(")")
            appendLine()
            // Per-segment easings: segment i departs from keyframe i, so easings are indexed the
            // same way (Cycle's wrap segment uses the last keyframe's outgoing easing).
            val segmentEasings = List(segments) { index ->
                state.easings.getOrElse(index) { SegmentEasing.Linear }
            }
            val hasEasing = segmentEasings.any { it != SegmentEasing.Linear }
            if (hasEasing) {
                appendLine("// Per-segment easing: entry i shapes the transition out of keyframe i.")
                appendLine("private val segmentEasings: List<(Float) -> Float> = listOf(")
                segmentEasings.forEach { easing ->
                    appendLine("    ${easingLambdaSource(easing)}, // ${easing.label}")
                }
                appendLine(")")
                appendLine()
            }
            val localT =
                if (hasEasing) "segmentEasings[index](scaled - index)" else "scaled - index"
            appendLine("private fun sampleFrame(frames: List<MeshFrame>, progress: Float): MeshFrame {")
            appendLine("    if (frames.size == 1) return frames[0]")
            appendLine("    val segments = frames.size - 1")
            appendLine("    val scaled = progress.coerceIn(0f, 1f) * segments")
            appendLine("    val index = scaled.toInt().coerceAtMost(segments - 1)")
            appendLine("    return lerpFrame(frames[index], frames[index + 1], $localT)")
            appendLine("}")
            appendLine()

            // Composable entry point.
            appendLine("@Composable")
            appendLine("fun MeshGradient(modifier: Modifier = Modifier) {")
            appendLine("    val transition = rememberInfiniteTransition()")
            appendLine("    val progress by transition.animateFloat(")
            appendLine("        initialValue = 0f,")
            appendLine("        targetValue = 1f,")
            appendLine("        animationSpec = infiniteRepeatable(")
            appendLine("            animation = tween(durationMillis = $totalDuration, easing = LinearEasing),")
            appendLine("            repeatMode = RepeatMode.$repeatMode,")
            appendLine("        ),")
            appendLine("    )")
            appendLine("    // MeshGradientPainter runs this block on every draw. Reading `progress`")
            appendLine("    // (snapshot state) inside it means each animation frame invalidates the")
            appendLine("    // draw phase only: no recomposition and no painter re-allocation.")
            appendLine("    val painter = remember {")
            append("        MeshGradientPainter(")
            append("rows = $rows, columns = $columns, ")
            appendLine("hasBicubicColor = ${state.hasBicubicColor}) {")
            appendLine("            val frame = sampleFrame(keyframes, progress)")
            appendLine("            for (row in 0..$rows) {")
            appendLine("                for (column in 0..$columns) {")
            appendLine("                    val index = row * (${columns} + 1) + column")
            appendLine("                    setVertex(")
            appendLine("                        row,")
            appendLine("                        column,")
            appendLine("                        position = frame.positions[index],")
            appendLine("                        color = frame.colors[index],")
            appendLine("                        leftControlPoint = frame.left[index],")
            appendLine("                        topControlPoint = frame.top[index],")
            appendLine("                        rightControlPoint = frame.right[index],")
            appendLine("                        bottomControlPoint = frame.bottom[index],")
            appendLine("                    )")
            appendLine("                }")
            appendLine("            }")
            appendLine("        }")
            appendLine("    }")
            appendLine("    Box(modifier.fillMaxSize().paint(painter))")
            append("}")
        }

    /**
     * A `(Float) -> Float` lambda literal for [easing]. Must stay mathematically identical to
     * [SegmentEasing.transform] so the pasted code reproduces the preview exactly.
     */
    private fun easingLambdaSource(easing: SegmentEasing): String = when (easing) {
        SegmentEasing.Linear -> "{ t -> t }"
        SegmentEasing.EaseIn -> "{ t -> t * t * t }"
        SegmentEasing.EaseOut -> "{ t -> val inv = 1f - t; 1f - inv * inv * inv }"
        SegmentEasing.EaseInOut ->
            "{ t -> if (t < 0.5f) 4f * t * t * t else { val inv = -2f * t + 2f; 1f - inv * inv * inv / 2f } }"
    }

    private fun offsetList(offsets: List<Offset>): String =
        offsets.joinToString(prefix = "listOf(", postfix = ")") { formatOffset(it) }

    private fun colorList(colors: List<Color>): String =
        colors.joinToString(prefix = "listOf(", postfix = ")") { formatColor(it) }

    private fun resolvedBezierList(offsets: List<Offset>, direction: BezierDirection): String =
        offsets.joinToString(prefix = "listOf(", postfix = ")") {
            formatOffset(MeshInterpolator.resolveBezier(it, direction))
        }

    /** Builds a single `setVertex(...)` call, omitting unspecified bezier control points. */
    internal fun vertexCall(mesh: MeshData, row: Int, column: Int): String {
        val index = mesh.indexOf(row, column)
        val args = mutableListOf(
            "$row",
            "$column",
            "position = ${formatOffset(mesh.positions[index])}",
            "color = ${formatColor(mesh.colors[index])}",
        )
        for (direction in BezierDirection.entries) {
            val offset = mesh.bezierOffset(index, direction)
            if (offset != Offset.Unspecified) {
                args += "${direction.argName()} = ${formatOffset(offset)}"
            }
        }
        return "setVertex(${args.joinToString(", ")})"
    }

    private fun BezierDirection.argName(): String = when (this) {
        BezierDirection.LEFT -> "leftControlPoint"
        BezierDirection.TOP -> "topControlPoint"
        BezierDirection.RIGHT -> "rightControlPoint"
        BezierDirection.BOTTOM -> "bottomControlPoint"
    }

    /** Formats an [Offset] as `Offset(xf, yf)`. */
    internal fun formatOffset(offset: Offset): String =
        "Offset(${formatFloat(offset.x)}, ${formatFloat(offset.y)})"

    /** Formats a [Color] as `Color(0xAARRGGBB)` with upper-case hex. */
    internal fun formatColor(color: Color): String {
        val a = (color.alpha * 255f).roundToInt().coerceIn(0, 255)
        val r = (color.red * 255f).roundToInt().coerceIn(0, 255)
        val g = (color.green * 255f).roundToInt().coerceIn(0, 255)
        val b = (color.blue * 255f).roundToInt().coerceIn(0, 255)
        val argb = (a.toLong() shl 24) or (r.toLong() shl 16) or (g.toLong() shl 8) or b.toLong()
        val hex = argb.toString(16).uppercase().padStart(8, '0')
        return "Color(0x$hex)"
    }

    /**
     * Formats a [Float] with an `f` suffix, rounded to at most 4 decimals with trailing zeros
     * trimmed. Non-finite values fall back to `0f`.
     */
    internal fun formatFloat(value: Float): String {
        if (value.isNaN() || value.isInfinite()) return "0f"
        val scaled = round(value.toDouble() * 10_000.0).toLong()
        if (scaled == 0L) return "0f"
        val negative = scaled < 0
        val absScaled = abs(scaled)
        val intPart = absScaled / 10_000
        val fracPart = absScaled % 10_000
        return buildString {
            if (negative) append('-')
            append(intPart)
            if (fracPart != 0L) {
                val frac = fracPart.toString().padStart(4, '0').trimEnd('0')
                append('.').append(frac)
            }
            append('f')
        }
    }
}
